# Generated by Django 3.0.2 on 2020-06-14 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200515_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='introduction',
            field=models.CharField(default=1, max_length=280),
        ),
    ]
