# Generated by Django 3.0.2 on 2020-11-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200627_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='introduction',
            field=models.CharField(max_length=280),
        ),
    ]
