# Generated by Django 3.0.2 on 2020-03-10 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safaripackages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='safaripackages',
            options={'verbose_name': 'Safari Entry', 'verbose_name_plural': 'Safari Entries'},
        ),
        migrations.AddField(
            model_name='safaripackages',
            name='slug',
            field=models.SlugField(default=True, max_length=200, unique=True),
        ),
    ]
