# Generated by Django 3.0.2 on 2020-03-10 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safaripackages', '0003_auto_20200311_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='safaripackages',
            name='image',
            field=models.ImageField(default=False, upload_to='SafariPackages/%Y/%m/%d'),
        ),
    ]
