# Generated by Django 3.0.2 on 2020-03-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safaripackages', '0004_safaripackages_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='safaripackages',
            name='telegram',
            field=models.TextField(default=False, max_length=140),
        ),
    ]
