# Generated by Django 3.0.2 on 2020-03-15 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safaripackages', '0006_auto_20200315_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safaripackages',
            name='image',
            field=models.ImageField(upload_to='SafariPackages/%Y/%m/%d'),
        ),
    ]
