# Generated by Django 3.0.2 on 2020-05-15 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safaripackages', '0007_auto_20200315_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='safaripackages',
            name='nights',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='safaripackages',
            name='days',
            field=models.FloatField(null=True),
        ),
    ]
