# Generated by Django 3.0.2 on 2020-05-15 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safaripackages', '0013_auto_20200515_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safaripackages',
            name='days',
            field=models.FloatField(default=False),
        ),
        migrations.AlterField(
            model_name='safaripackages',
            name='nights',
            field=models.FloatField(default=False),
        ),
    ]
