# Generated by Django 3.0.2 on 2020-05-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safaripackages', '0014_auto_20200515_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safaripackages',
            name='days',
            field=models.FloatField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='safaripackages',
            name='nights',
            field=models.FloatField(default=False, null=True),
        ),
    ]
