# Generated by Django 3.0.2 on 2020-05-15 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safaripackages', '0015_auto_20200515_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safaripackages',
            name='days',
            field=models.FloatField(default=False),
        ),
        migrations.AlterField(
            model_name='safaripackages',
            name='nights',
            field=models.FloatField(default=False),
        ),
    ]
