# Generated by Django 3.0.2 on 2020-05-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safaripackages', '0017_auto_20200515_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='safaripackages',
            name='days',
            field=models.FloatField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='safaripackages',
            name='nights',
            field=models.FloatField(blank=True, default=True, null=True),
        ),
    ]
