# Generated by Django 3.0.2 on 2020-05-20 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safaripackages', '0019_auto_20200515_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafariKalesaPackages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='SafariPackages/%Y/%m/%d')),
                ('title', models.CharField(max_length=200)),
                ('cost', models.FloatField()),
                ('days', models.FloatField()),
                ('nights', models.FloatField()),
                ('exodus', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('telegram', models.TextField(max_length=140)),
                ('description', models.TextField()),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Kalessa Package Entry',
                'verbose_name_plural': 'Kalessa Package Entries',
            },
        ),
        migrations.AlterModelOptions(
            name='safaripackages',
            options={'verbose_name': 'Safari Package Entry', 'verbose_name_plural': 'Safari Package Entries'},
        ),
    ]
