# Generated by Django 3.0.2 on 2020-05-20 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('safaripackages', '0021_auto_20200520_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.TextField()),
            ],
            options={
                'verbose_name': 'Safari Package Entry',
                'verbose_name_plural': 'Safari Package Entries',
            },
        ),
        migrations.DeleteModel(
            name='SafariKalesaPackages',
        ),
        migrations.AlterModelOptions(
            name='safaripackages',
            options={},
        ),
        migrations.AddField(
            model_name='daynumber',
            name='safaripackages',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siku', to='safaripackages.SafariPackages'),
        ),
    ]
