# Generated by Django 3.0.2 on 2020-05-20 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safaripackages', '0022_auto_20200520_2146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='daynumber',
            options={},
        ),
        migrations.AlterModelOptions(
            name='safaripackages',
            options={'verbose_name': 'Safari Package Entry', 'verbose_name_plural': 'Safari Package Entries'},
        ),
    ]
