# Generated by Django 3.0.2 on 2020-05-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safaripackages', '0023_auto_20200520_2159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daynumber',
            old_name='day',
            new_name='day_description',
        ),
        migrations.AddField(
            model_name='daynumber',
            name='day_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
