# Generated by Django 3.0.2 on 2020-05-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safaripackages', '0024_auto_20200524_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daynumber',
            name='day_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
