# Generated by Django 3.0.2 on 2020-05-28 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('safaripackages', '0025_auto_20200525_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='daynumber',
            name='image',
            field=models.ImageField(default=1, upload_to='SafariPackages/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='daynumber',
            name='safaripackages',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daynumber', to='safaripackages.SafariPackages'),
        ),
    ]
