# Generated by Django 3.0.2 on 2020-05-29 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('safaripackages', '0026_auto_20200529_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daynumber',
            name='safaripackages',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daynumber', to='safaripackages.SafariPackages', verbose_name='Day Details'),
        ),
    ]
