# Generated by Django 3.0.2 on 2020-05-30 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('safaripackages', '0028_auto_20200529_0329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daynumber',
            name='safaripackages',
        ),
        migrations.AddField(
            model_name='daynumber',
            name='daydetails',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='daydetails', to='safaripackages.SafariPackages'),
        ),
        migrations.AlterField(
            model_name='daynumber',
            name='image',
            field=models.ImageField(default=1, upload_to='SafariPackagesDetails/%Y/%m/%d'),
        ),
    ]
