# Generated by Django 3.0.2 on 2020-06-01 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safaripackages', '0029_auto_20200530_0957'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='safaripackages',
            old_name='description',
            new_name='brief_description',
        ),
        migrations.RenameField(
            model_name='safaripackages',
            old_name='telegram',
            new_name='overview',
        ),
    ]
