# Generated by Django 3.0.2 on 2020-11-09 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safaripackages', '0032_daynumber_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daynumber',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
